DROP TABLE IF EXISTS {cluster_desc_table_name};

CREATE TABLE {cluster_desc_table_name} AS
WITH ICD_LONG AS
(SELECT ICD9_DGNS_CD_1 AS ICD9_DGNS_CD, DIAGNOSIS_CLUSTER FROM T_SYNPUF_OUTPATIENT_CLAIMS_CLUSTERS WHERE ICD9_DGNS_CD_1 IS NOT NULL
UNION ALL
SELECT ICD9_DGNS_CD_2  AS ICD9_DGNS_CD, DIAGNOSIS_CLUSTER FROM T_SYNPUF_OUTPATIENT_CLAIMS_CLUSTERS WHERE ICD9_DGNS_CD_2 IS NOT NULL
UNION ALL
SELECT ICD9_DGNS_CD_3  AS ICD9_DGNS_CD, DIAGNOSIS_CLUSTER FROM T_SYNPUF_OUTPATIENT_CLAIMS_CLUSTERS WHERE ICD9_DGNS_CD_3 IS NOT NULL
UNION ALL
SELECT ICD9_DGNS_CD_4  AS ICD9_DGNS_CD, DIAGNOSIS_CLUSTER FROM T_SYNPUF_OUTPATIENT_CLAIMS_CLUSTERS WHERE ICD9_DGNS_CD_4 IS NOT NULL),

ICD_CLUSTER_COUNTS AS
(SELECT
	DIAGNOSIS_CLUSTER
	, ICD9_DGNS_CD
	, COUNT(*) AS FREQ
FROM
	ICD_LONG
GROUP BY 
	DIAGNOSIS_CLUSTER
	, ICD9_DGNS_CD),
	
ICD_CLUSTER_TOTALS AS
(SELECT
	DIAGNOSIS_CLUSTER
	, ICD9_DGNS_CD
	, FREQ
	, ROW_NUMBER() OVER (PARTITION BY DIAGNOSIS_CLUSTER ORDER BY FREQ DESC) AS RN
FROM
	ICD_CLUSTER_COUNTS)
	
SELECT
	A.DIAGNOSIS_CLUSTER
	, A.ICD9_DGNS_CD
	, B.ICD9_DESC
	, A.FREQ
	, A.RN AS RANKING
FROM
	ICD_CLUSTER_TOTALS A
INNER JOIN
	{descriptions_table_name} B
	ON A.ICD9_DGNS_CD = B.ICD9_CODE
WHERE
	RN <= 10