DROP TABLE IF EXISTS {cluster_pmt_totals_table_name};

CREATE TABLE {cluster_pmt_totals_table_name} AS
WITH CLAIM_MONTHS AS
(SELECT
	CLM_ID
	, DATE(CLM_FROM_DT, 'start of month') AS CLM_FROM_MONTH
FROM
	{claims_table_name}
WHERE
	CLM_FROM_MONTH IS NOT NULL),
	
CLAIM_TOTALS AS
(SELECT
	CLM_ID
	, SUM(CLM_PMT_AMT) AS CLM_PMT_AMT_TOTAL
FROM
	{claims_table_name}
GROUP BY
	CLM_ID)
	
SELECT
	A.CLM_FROM_MONTH
	, C.DIAGNOSIS_CLUSTER
	, COUNT(*) AS NUM_CLAIMS
	, SUM(B.CLM_PMT_AMT_TOTAL) AS CLM_PMT_AMT_TOTAL
FROM
	CLAIM_MONTHS A
INNER JOIN 
	CLAIM_TOTALS B
	ON A.CLM_ID = B.CLM_ID
INNER JOIN
	{clusters_table_name} C
	ON A.CLM_ID = C.CLM_ID
GROUP BY
	A.CLM_FROM_MONTH
	, C.DIAGNOSIS_CLUSTER